services:
  php:
    image: naegato/php-symfony:php8.4.1-postgres
    volumes:
      - .:/srv:cached
    depends_on:
      - db

  web:
    build:
      context: ./docker/nginx
    volumes:
      - .:/srv:cached
    environment:
      fastcgi_pass: php:9000
    depends_on:
      - php

  db:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-app}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${DB_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  node:
    image: node:23-alpine
    volumes:
      - .:/srv:cached
    working_dir: /srv
    command: tail -f /dev/null

#  mailbox:
#    image: dockage/mailcatcher

#  adminer:
#    image: adminer:4.8.1

volumes:
  db_data: